name: Copy Selected Files to Another Repo

on:
  push:
    branches:
      - main  # Change if you want to copy from a different branch

jobs:
  copy-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .gitignore
          src
          index.html
          public
          README.md
          package.json
          eslint.config.js
          vite.config.js

    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        repository: sumit-sen-cf/jarvis-frontend-2
        token: ${{ secrets.PAT_AUTH }}
        path: target-repo
        ref: main
        fetch-depth: 0  # Fetch all history for detecting if repo is empty

    - name: Check if target repo is empty
      id: check_empty
      run: |
        if [ -z "$(ls -A target-repo)" ]; then
          echo "empty=true" >> $GITHUB_ENV
        else
          echo "empty=false" >> $GITHUB_ENV
        fi

    - name: Copy selected files from source to target
      run: |
        cp -r src index.html public README.md package.json eslint.config.js vite.config.js .gitignore target-repo/

    - name: Commit and push changes
      run: |
        cd target-repo
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        if [ "${{ env.empty }}" == "true" ]; then
          git commit -m "Initial commit from source repo"
          git branch -M main
          git push -u origin main
        else
          git commit -m "Sync selected files from source repo"
          git push origin main
        fi
      env:
        PAT_AUTH: ${{ secrets.PAT_AUTH }}
