name: Copy Repo to Another Repo

on:
  push:
    branches:
      - main  # Change if you want to copy from a different branch

jobs:
  copy-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Add destination repo as remote
      run: |
        git remote add destination https://github.com/Pratyushg1312/citest.git
        git fetch destination
    - name: check branch
      run: |
        git remote -v      

    - name: Push to destination repo
      run: |
        git push  destination main:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
