name: Copy Selected Files to Another Repo

on:
  push:
    branches:
      - main  # Change if you want to copy from a different branch

jobs:
  copy-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github
          src
          index.html
          public
          README.md
          package.json
          eslint.config.js
          vite.config.js

    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        repository: Pratyushg1312/citest
        token: ${{ secrets.PAT_AUTH }}
        path: target-repo

    - name: Copy selected files from source to target
      run: |
        cp -r .github src index.html public README.md package.json eslint.config.js vite.config.js target-repo/
        cd target-repo
        git config user.name "pratyush"
        git config user.email "pratyushg095@gmail.com"
        git add .
        git commit -m "Sync selected files from source repo"
        git push origin main
      env:
        PAT_AUTH: ${{ secrets.PAT_AUTH }}
